include:
  - project: 'synechron-code/cloud-devops/templates/pipeline-templates'
    ref: latest
    file:
      - /templates/jobs/.backstage-publish-docs.yaml
      - /templates/jobs/.acr-build.yaml
      - /templates/jobs/.python-dependency-check.yaml
      - /templates/jobs/.sast-check.yaml
      # - /templates/jobs/.code-quality-check.yaml
      - /templates/jobs/.markdownlint.yaml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SEM_VER: $CI_COMMIT_TAG
  ACR_REGISTRY: "synecloudpracticeprodacr"
  AZURE_CLIENT_ID: $AZURE_PROD_CLIENT_ID
  AZURE_CLIENT_SECRET: $AZURE_PROD_CLIENT_SECRET
  AZURE_TENANT_ID: $ARM_TENANT_ID

stages:
  - test
  - prepare
  - build
  - document

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

dockerfile_lint:
  allow_failure: true
  stage: test
  image: registry.gitlab.com/pipeline-components/hadolint:latest
  script:
    - hadolint "Dockerfile"

markdownlint:
  allow_failure: true

# TODO add this to a pipeline template
get_certs:
  stage: prepare
  image:
    name: ubuntu:latest
    entrypoint: [ "" ]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: '$CI_COMMIT_TAG != null'
  before_script:
    - apt-get update && apt-get install -y curl openssl
  script:
    # See https://learn.microsoft.com/en-gb/azure/postgresql/flexible-server/concepts-networking-ssl-tls#download-root-ca-certificates-and-update-application-clients-in-certificate-pinning-scenarios
    - curl -LO https://www.microsoft.com/pkiops/certs/Microsoft%20RSA%20Root%20Certificate%20Authority%202017.crt
    - curl -LO https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
    - curl -LO https://cacerts.digicert.com/DigiCertGlobalRootCA.crt
    - openssl x509 -inform DER -in DigiCertGlobalRootCA.crt -out DigiCertGlobalRootCA.pem -outform PEM
    - openssl x509 -inform DER -in Microsoft%20RSA%20Root%20Certificate%20Authority%202017.crt -out Microsoft%20RSA%20Root%20Certificate%20Authority%202017.pem -outform PEM
  artifacts:
    paths:
      - Microsoft%20RSA%20Root%20Certificate%20Authority%202017.pem
      - DigiCertGlobalRootG2.crt.pem
      - DigiCertGlobalRootCA.pem

get_token:
  tags:
    - icp

build_image:
  dependencies:
    - get_certs
  tags:
    - icp
