---
ul-style:
  style: "dash"
no-trailing-punctuation:
  "punctuation": ".,;:"
line-length: false
no-inline-html: false
no-bare-urls: false
blanks-around-headings: false
single-trailing-newline: false
